@startuml
!theme cloudscape from /Users/brianweber/Downloads/oauth2-diagrams/themes

!pragma teoz true

participant "Client\nhttps://client" as client
box
    participant "User Agent / Frontend\nfor Client" as uac
    actor "Resource Owner\n(User)" as user
    participant "User Agent / Frontend for\nAuthorization Server" as uaas
end box
participant "Authorization Server\nhttps://as" as as
participant "Resource Server\nhttps://rs" as rs

user -> uac: Request to authorize resource access
& uac -> client

client -> uac
& uac -> user: Prompt login and password

user -> uac: Login and password
& uac -> client


|||

& client -> as: **Access Token Request**\nPOST https://as/token (token_endpoint)\n  ?grant_type=password (REQUIRED)\n  &username=johndoe\n  &password=iloveyou\n  &scope=scope1+scope2 (OPTIONAL)\n  &resource=http://rs/api (extension, API base URI)\n  &authorization_details=[{"type": "…", …}, …] (extension, see draft-ietf-oauth-rar)\n(with some form of client authentication)

as --> client: **Access Token Response**\nHTTPS 200 OK, JSON\n"access_token": "AT-XXXX", (⚠️ NO refresh_token!)\n"token_type": "bearer",\n"expires_in": 3600,\n"scope": "scope1 scope2"

@enduml

